spring.application.name: greenlight-scheduler
spring.profiles.active: local

server:
  port: 27070
  url: ${SERVER_URL}

springdoc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

spring:
  config:
    import: optional:file:.env[.properties]

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: INFO
    com.winten: DEBUG

influxdb:
  url: ${INFLUXDB_URL}
  token: ${INFLUXDB_TOKEN}
  org: ${INFLUXDB_ORG}
  bucket: ${INFLUXDB_BUCKET}

redis:
  key-prefix: ${REDIS_KEY_PREFIX}
  connection-type: ${REDIS_CONNECTION_TYPE:standalone}

---

spring.config.activate.on-profile: local
spring:
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}
      password: ${REDIS_PASSWORD}

---

spring.config.activate.on-profile: dev
spring:
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}
      password: ${REDIS_PASSWORD}

---

spring.config.activate.on-profile: live
spring:
  data:
    redis:
      cluster:
        max-redirects: 3
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: ERROR
    com.winten: ERROR
    com.winten.greenlight.scheduler: ERROR
    org.springframework.data.redis: ERROR