server:
  port: 27070

spring:
  application:
    name: greenlight-scheduler
  profiles:
    active: local
  url: ${SERVER_URL}

springdoc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
    -

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: INFO
    com.winten: DEBUG

---

spring.config.activate.on-profile: local
spring:
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
      key-prefix: ${REDIS_KEY_PREFIX}

---

spring.config.activate.on-profile: dev
spring:
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
      key-prefix: ${REDIS_KEY_PREFIX}

---

spring.config.activate.on-profile: live
spring:
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
      key-prefix: ${REDIS_KEY_PREFIX}

logging:
  level:
    root: ERROR
    com.winten: ERROR
    com.winten.greenlight.scheduler: ERROR
    org.springframework.data.redis: ERROR